name: Deploy to Github Pages

on:
    schedule:
        - cron: '0 23 * * *' # runs at 01:00 UTC everyday
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install Packages
              run: |
                  npm i --legacy-peer-deps

            - name: Checkout
              uses: actions/checkout@v1

            - name: Build and Deploy
              uses: sau1707/gh-pages-deploy-action@v1.1
              with:
                  access-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  source-directory: out
                  build-command: npm run build && npm run export
                  custom-domain: coin.luganostats.com
