name: Deploy to Github Pages

on:
    schedule:
        - cron: '0 23 * * 1' # runs at 01:00 UTC everyday
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Build
              run: |
                  npm i --legacy-peer-deps
                  npm run build
                  npm run export
            - name: Add CNAME to directory
              run: echo coin.luganostats.com >> ./out/CNAME

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./out
